port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:6170
ipv6: true
unified-delay: false
tcp-concurrent: true
global-client-fingerprint: chrome
hosts:
  mtalk.google.com: 108.177.125.188
experimental:
  ignore-resolve-fail: true
cfw-latency-url: https://connectivitycheck.gstatic.com/generate_204
cfw-latency-type: 1
cfw-latency-timeout: 5000
cfw-conn-break-strategy: true
clash-for-android:
  append-system-dns: false
  ui-subtitle-pattern: "[一-龥]{2,4}"
url-rewrite:
  - ^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302
  - ^https?:\/\/(ditu|maps).google\.cn https://maps.google.com 302
sniffer:
  enable: true
  sniff:
    TLS: {ports: [1-65535], override-destination: true}
    HTTP: {ports: [1-65535], override-destination: true}
    QUIC: {ports: [1-65535], override-destination: true}
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - +.push.apple.com
  parse-pure-ip: false
  force-dns-mapping: true
  override-destination: true
dns:
  ipv6: false
  enable: false
  prefer-h3: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  use-hosts: false
  default-nameserver: [119.28.28.28, 119.29.29.29, 223.5.5.5, 223.6.6.6]
  nameserver: [119.29.29.29, 223.5.5.5, tls://dot.pub:853, tls://dns.alidns.com:853, https://doh.pub:443/dns-query, https://dns.alidns.com:443/dns-query]
  fallback: [https://dns.cloudflare.com/dns-query, https://doh.dns.sb/dns-query, tls://8.8.4.4:853]
  fallback-filter: {geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32]}
  fake-ip-range: 198.18.0.1/15
  fake-ip-filter: ["*.lan", "*.localdomain", "*.example", "*.invalid", "*.localhost", "*.test", "*.local"]
